version: '3.8'

networks:
  lexik_translation_network:
    driver: bridge

services:
  lexik_translation:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongo
    networks:
      - lexik_translation_network
    environment:
      - DOCKER=true
      - DB_HOST=mysql
      - MONGO_SERVER=mongodb://admin:secret@mongo:27017/admin

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lexik_translation_test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - lexik_translation_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - lexik_translation_network
